/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

/**
 *
 * @author MARLON
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.winnerGot.setVisible(false);
        this.winnerVelma.setVisible(false);
    }
    
    public void updateQueues(String[] strings){
        this.cola1GOT.setText(strings[0]);
        this.cola2GOT.setText(strings[1]);
        this.cola3GOT.setText(strings[2]);
        this.cola3BoostGOT.setText(strings[3]);
        this.cola1Velma.setText(strings[4]);
        this.cola2Velma.setText(strings[5]);
        this.cola3Velma.setText(strings[6]);
        this.colaBoostVelma.setText(strings[7]);
    }
    
    public void updateCharacters(String characterG, String characterV){
        this.perGOT.setText(characterG);
        this.perVelma.setText(characterV);
    }
    public void winnerVisibleGot(){
        this.winnerGot.setVisible(true);
        this.winnerVelma.setVisible(false);
    }
    public void winnerVisibleVelma(){
        this.winnerGot.setVisible(false);
        this.winnerVelma.setVisible(true);
    }
    public void resetWinner(){
        this.winnerGot.setVisible(false);
        this.winnerVelma.setVisible(false);
    }
    public void updateId(int got, int velma){
        this.GotId.setText(String.valueOf(got));
        this.VelmaId.setText(String.valueOf(velma));
    }
    public void updateCharStat(int statgot, int statvelma){
        this.GotStat.setText(String.valueOf(statgot));
        this.VelmaStat.setText(String.valueOf(statvelma));
    }
    public void updateStats(int stat){
        switch (stat) {
            case 1:
                this.stat.setText("Fuerza");
                break;
            case 2:
                this.stat.setText("Inteligencia");
                break;
            case 3:
                this.stat.setText("Armas");
                break;
            case 4:
                this.stat.setText("Velocidad");
                break;
            case 5:
                this.stat.setText("Resistencia");
            default:
                this.stat.setText("----------");
                break;
        }
    }
        public void updateVisibleEmpate(boolean visible){
            this.empate.setVisible(visible);
        }
        public void updateVisibleRefuerzo(boolean visible){
            this.refuerzo.setVisible(visible);
        }
        public void updatePuntuacion(){
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cola3BoostGOT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        colaBoostVelma = new javax.swing.JLabel();
        cola1GOT = new javax.swing.JLabel();
        cola2GOT = new javax.swing.JLabel();
        cola3GOT = new javax.swing.JLabel();
        cola1Velma = new javax.swing.JLabel();
        cola2Velma = new javax.swing.JLabel();
        cola3Velma = new javax.swing.JLabel();
        fightPanel = new javax.swing.JPanel();
        perVelma = new javax.swing.JLabel();
        perGOT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VelmaStat = new javax.swing.JLabel();
        GotStat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        winnerGot = new javax.swing.JLabel();
        winnerVelma = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        GotId = new javax.swing.JLabel();
        VelmaId = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        refuerzo = new javax.swing.JLabel();
        empate = new javax.swing.JLabel();
        puntosGot = new javax.swing.JLabel();
        puntosVelma = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Velma");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("GOT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setText("Colas de prioridad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("    3");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 50, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("    2");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("    1");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 50, -1));

        cola3BoostGOT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola3BoostGOT.setOpaque(true);
        jPanel1.add(cola3BoostGOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 400, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("boost");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 50, -1));

        colaBoostVelma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colaBoostVelma.setOpaque(true);
        jPanel1.add(colaBoostVelma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 390, 30));

        cola1GOT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola1GOT.setOpaque(true);
        jPanel1.add(cola1GOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, 30));

        cola2GOT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola2GOT.setOpaque(true);
        jPanel1.add(cola2GOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 30));

        cola3GOT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola3GOT.setOpaque(true);
        jPanel1.add(cola3GOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 400, 30));

        cola1Velma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola1Velma.setOpaque(true);
        jPanel1.add(cola1Velma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 390, 30));

        cola2Velma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola2Velma.setOpaque(true);
        jPanel1.add(cola2Velma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 390, 30));

        cola3Velma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cola3Velma.setOpaque(true);
        jPanel1.add(cola3Velma, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 390, 30));

        fightPanel.setBackground(new java.awt.Color(204, 255, 255));
        fightPanel.setBorder(new javax.swing.border.MatteBorder(null));
        fightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perVelma.setBackground(new java.awt.Color(255, 255, 102));
        perVelma.setOpaque(true);
        fightPanel.add(perVelma, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 110));

        perGOT.setBackground(new java.awt.Color(255, 255, 102));
        perGOT.setOpaque(true);
        fightPanel.add(perGOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 110));

        jLabel4.setText("Fight Stat");
        fightPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        VelmaStat.setText("-");
        fightPanel.add(VelmaStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 20, -1));

        GotStat.setText("-");
        fightPanel.add(GotStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 20, -1));

        jLabel6.setText("vs");
        fightPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        stat.setText("-------------------------");
        fightPanel.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 150, -1));

        winnerGot.setText("winner");
        fightPanel.add(winnerGot, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        winnerVelma.setText("winner");
        fightPanel.add(winnerVelma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel11.setText("id");
        fightPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        GotId.setText("0");
        fightPanel.add(GotId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, -1));

        VelmaId.setText("0");
        fightPanel.add(VelmaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 70, -1));

        jLabel12.setText("id");
        fightPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        refuerzo.setText("Refuerzo");
        fightPanel.add(refuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        empate.setText("Empate");
        fightPanel.add(empate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        puntosGot.setText("0");
        fightPanel.add(puntosGot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, -1));

        puntosVelma.setText("0");
        fightPanel.add(puntosVelma, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 50, -1));

        jPanel1.add(fightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 640, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rick-and-morty-wallpaper-1024x768-wallpaper.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GotId;
    private javax.swing.JLabel GotStat;
    private javax.swing.JLabel VelmaId;
    private javax.swing.JLabel VelmaStat;
    private javax.swing.JLabel cola1GOT;
    private javax.swing.JLabel cola1Velma;
    private javax.swing.JLabel cola2GOT;
    private javax.swing.JLabel cola2Velma;
    private javax.swing.JLabel cola3BoostGOT;
    private javax.swing.JLabel cola3GOT;
    private javax.swing.JLabel cola3Velma;
    private javax.swing.JLabel colaBoostVelma;
    private javax.swing.JLabel empate;
    private javax.swing.JPanel fightPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel perGOT;
    private javax.swing.JLabel perVelma;
    private javax.swing.JLabel puntosGot;
    private javax.swing.JLabel puntosVelma;
    private javax.swing.JLabel refuerzo;
    private javax.swing.JLabel stat;
    private javax.swing.JLabel winnerGot;
    private javax.swing.JLabel winnerVelma;
    // End of variables declaration//GEN-END:variables
}
